<?php
/**
 * ACF fields for IntelliMortise Product Template
 */

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group(array(
        'key' => 'group_intelli_mortise_template',
        'title' => 'IntelliMortise Product Template',
        'fields' => array(
            // Hero Section
            array(
                'key' => 'field_mortise_hero_section',
                'label' => 'Hero Section',
                'name' => 'mortise_hero_section',
                'type' => 'group',
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'field_mortise_product_title',
                        'label' => 'Product Title',
                        'name' => 'product_title',
                        'type' => 'text',
                        'default_value' => 'Meet IntelliMortise – flagship smart security for primary doors',
                        'required' => 1,
                    ),
                    array(
                        'key' => 'field_mortise_product_intro',
                        'label' => 'Product Introduction',
                        'name' => 'product_intro',
                        'type' => 'textarea',
                        'default_value' => 'Engineered for high-traffic guest entries, IntelliMortise blends hotel-grade durability with sleek styling in brushed stainless or satin black. Choose a capacitive touchscreen or tactile push-button keypad and upgrade new builds or retrofits in under 15 minutes—no wiring required.',
                        'rows' => 3,
                        'required' => 0,
                    ),
                    array(
                        'key' => 'field_mortise_hero_image',
                        'label' => 'Hero Image',
                        'name' => 'hero_image',
                        'type' => 'image',
                        'return_format' => 'url',
                        'preview_size' => 'medium',
                        'instructions' => 'Upload the main product image (recommended: 800x800px)',
                        'required' => 0,
                    ),
                    array(
                        'key' => 'field_mortise_specs_button_text',
                        'label' => 'Specifications Button Text',
                        'name' => 'specs_button_text',
                        'type' => 'text',
                        'default_value' => 'View Specs',
                        'required' => 0,
                    ),
                    array(
                        'key' => 'field_mortise_quote_button_text',
                        'label' => 'Quote Button Text',
                        'name' => 'quote_button_text',
                        'type' => 'text',
                        'default_value' => 'Get a Quote',
                        'required' => 0,
                    ),
                    array(
                        'key' => 'field_mortise_quote_button_url',
                        'label' => 'Quote Button URL',
                        'name' => 'quote_button_url',
                        'type' => 'text',
                        'default_value' => '#quote',
                        'required' => 0,
                    ),
                ),
            ),
            
            // Benefits Section
            array(
                'key' => 'field_mortise_benefits_section',
                'label' => 'Benefits Section',
                'name' => 'mortise_benefits_section',
                'type' => 'group',
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'field_mortise_benefits_title',
                        'label' => 'Benefits Section Title',
                        'name' => 'benefits_title',
                        'type' => 'text',
                        'default_value' => 'Why properties choose IntelliMortise',
                        'required' => 0,
                    ),
                    array(
                        'key' => 'field_mortise_benefits',
                        'label' => 'Benefits',
                        'name' => 'benefits',
                        'type' => 'repeater',
                        'layout' => 'block',
                        'min' => 0,
                        'max' => 6,
                        'button_label' => 'Add Benefit',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_mortise_benefit_icon',
                                'label' => 'Benefit Icon (SVG)',
                                'name' => 'benefit_icon',
                                'type' => 'textarea',
                                'rows' => 3,
                                'instructions' => 'Enter SVG code for the icon (24x24 viewBox recommended)',
                                'required' => 0,
                            ),
                            array(
                                'key' => 'field_mortise_benefit_title',
                                'label' => 'Benefit Title',
                                'name' => 'benefit_title',
                                'type' => 'text',
                                'required' => 0,
                            ),
                            array(
                                'key' => 'field_mortise_benefit_description',
                                'label' => 'Benefit Description',
                                'name' => 'benefit_description',
                                'type' => 'textarea',
                                'rows' => 3,
                                'required' => 0,
                            ),
                        ),
                    ),
                ),
            ),
            
            // Specifications Section
            array(
                'key' => 'field_mortise_specs_section',
                'label' => 'Specifications Section',
                'name' => 'mortise_specs_section',
                'type' => 'group',
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'field_mortise_specs_title',
                        'label' => 'Specifications Section Title',
                        'name' => 'specs_title',
                        'type' => 'text',
                        'default_value' => 'At-a-Glance Specifications',
                        'required' => 0,
                    ),
                    array(
                        'key' => 'field_mortise_specs',
                        'label' => 'Specifications',
                        'name' => 'specs',
                        'type' => 'repeater',
                        'layout' => 'table',
                        'min' => 0,
                        'button_label' => 'Add Specification',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_mortise_spec_name',
                                'label' => 'Specification Name',
                                'name' => 'spec_name',
                                'type' => 'text',
                                'required' => 0,
                            ),
                            array(
                                'key' => 'field_mortise_spec_value',
                                'label' => 'Specification Value',
                                'name' => 'spec_value',
                                'type' => 'text',
                                'required' => 0,
                            ),
                        ),
                    ),
                ),
            ),
            
            // Features Section
            array(
                'key' => 'field_mortise_features_section',
                'label' => 'Features Section',
                'name' => 'mortise_features_section',
                'type' => 'group',
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'field_mortise_features_title',
                        'label' => 'Features Section Title',
                        'name' => 'features_title',
                        'type' => 'text',
                        'default_value' => 'Feature Checklist',
                        'required' => 0,
                    ),
                    array(
                        'key' => 'field_mortise_features',
                        'label' => 'Features',
                        'name' => 'features',
                        'type' => 'repeater',
                        'layout' => 'table',
                        'min' => 0,
                        'button_label' => 'Add Feature',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_mortise_feature_text',
                                'label' => 'Feature Text',
                                'name' => 'feature_text',
                                'type' => 'text',
                                'required' => 0,
                            ),
                        ),
                    ),
                ),
            ),
            
            // Use Cases Section
            array(
                'key' => 'field_mortise_use_cases_section',
                'label' => 'Use Cases Section',
                'name' => 'mortise_use_cases_section',
                'type' => 'group',
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'field_mortise_use_cases_title',
                        'label' => 'Use Cases Section Title',
                        'name' => 'use_cases_title',
                        'type' => 'text',
                        'default_value' => 'Perfect for…',
                        'required' => 0,
                    ),
                    array(
                        'key' => 'field_mortise_use_cases',
                        'label' => 'Use Cases',
                        'name' => 'use_cases',
                        'type' => 'repeater',
                        'layout' => 'table',
                        'min' => 0,
                        'button_label' => 'Add Use Case',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_mortise_use_case_text',
                                'label' => 'Use Case Text',
                                'name' => 'use_case_text',
                                'type' => 'text',
                                'required' => 0,
                            ),
                        ),
                    ),
                ),
            ),
            
            // CTA Section
            array(
                'key' => 'field_mortise_cta_section',
                'label' => 'CTA Section',
                'name' => 'mortise_cta_section',
                'type' => 'group',
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'field_mortise_cta_title',
                        'label' => 'CTA Title',
                        'name' => 'cta_title',
                        'type' => 'text',
                        'default_value' => 'See it in action',
                        'required' => 0,
                    ),
                    array(
                        'key' => 'field_mortise_cta_text',
                        'label' => 'CTA Text',
                        'name' => 'cta_text',
                        'type' => 'textarea',
                        'default_value' => 'Book a 10-minute demo or request a volume quote to discover how IntelliMortise upgrades security, cuts front-desk load, and delights every guest.',
                        'rows' => 3,
                        'required' => 0,
                    ),
                    array(
                        'key' => 'field_mortise_cta_supplement',
                        'label' => 'CTA Supplement Text',
                        'name' => 'cta_supplement',
                        'type' => 'textarea',
                        'default_value' => 'Bundle IntelliMortise for suites and IntelliLever for back-of-house to slash per-door costs while keeping a single management platform.',
                        'rows' => 3,
                        'required' => 0,
                    ),
                    array(
                        'key' => 'field_mortise_cta_button_text',
                        'label' => 'CTA Button Text',
                        'name' => 'cta_button_text',
                        'type' => 'text',
                        'default_value' => 'Request My Quote',
                        'required' => 0,
                    ),
                    array(
                        'key' => 'field_mortise_cta_button_url',
                        'label' => 'CTA Button URL',
                        'name' => 'cta_button_url',
                        'type' => 'text',
                        'default_value' => '/contact',
                        'required' => 0,
                    ),
                    array(
                        'key' => 'field_mortise_spec_sheet_button_text',
                        'label' => 'Spec Sheet Button Text',
                        'name' => 'spec_sheet_button_text',
                        'type' => 'text',
                        'default_value' => 'Download Spec Sheet',
                        'required' => 0,
                    ),
                    array(
                        'key' => 'field_mortise_spec_sheet_url',
                        'label' => 'Spec Sheet URL',
                        'name' => 'spec_sheet_url',
                        'type' => 'url',
                        'instructions' => 'Enter URL to the downloadable spec sheet',
                        'required' => 0,
                    ),
                ),
            ),
            
            // Compatibility Section
            array(
                'key' => 'field_mortise_compatibility_section',
                'label' => 'Compatibility Section',
                'name' => 'mortise_compatibility_section',
                'type' => 'group',
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'field_mortise_compatibility_title',
                        'label' => 'Compatibility Section Title',
                        'name' => 'compatibility_title',
                        'type' => 'text',
                        'default_value' => 'Door Compatibility Guide',
                        'required' => 0,
                    ),
                    // Standard Doors Tab
                    array(
                        'key' => 'field_mortise_standard_doors',
                        'label' => 'Standard Doors',
                        'name' => 'standard_doors',
                        'type' => 'group',
                        'layout' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_mortise_standard_title',
                                'label' => 'Standard Doors Title',
                                'name' => 'standard_title',
                                'type' => 'text',
                                'default_value' => 'Ideal for Primary Entrances',
                                'required' => 0,
                            ),
                            array(
                                'key' => 'field_mortise_standard_intro',
                                'label' => 'Standard Doors Introduction',
                                'name' => 'standard_intro',
                                'type' => 'textarea',
                                'default_value' => 'IntelliMortise is designed for exterior and primary entrance doors with these specifications:',
                                'rows' => 3,
                                'required' => 0,
                            ),
                            array(
                                'key' => 'field_mortise_standard_items',
                                'label' => 'Standard Door Items',
                                'name' => 'standard_items',
                                'type' => 'repeater',
                                'layout' => 'table',
                                'min' => 0,
                                'button_label' => 'Add Compatibility Item',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_mortise_standard_item_text',
                                        'label' => 'Item Text',
                                        'name' => 'item_text',
                                        'type' => 'text',
                                        'required' => 0,
                                    ),
                                ),
                            ),
                            array(
                                'key' => 'field_mortise_standard_conclusion',
                                'label' => 'Standard Doors Conclusion',
                                'name' => 'standard_conclusion',
                                'type' => 'textarea',
                                'default_value' => 'IntelliMortise delivers outstanding security and durability for primary entries, with flexible keypad options to match your design aesthetic.',
                                'rows' => 3,
                                'required' => 0,
                            ),
                        ),
                    ),
                    // Specialty Doors Tab
                    array(
                        'key' => 'field_mortise_specialty_doors',
                        'label' => 'Specialty Doors',
                        'name' => 'specialty_doors',
                        'type' => 'group',
                        'layout' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_mortise_specialty_title',
                                'label' => 'Specialty Doors Title',
                                'name' => 'specialty_title',
                                'type' => 'text',
                                'default_value' => 'Specialty Door Compatibility',
                                'required' => 0,
                            ),
                            array(
                                'key' => 'field_mortise_specialty_intro',
                                'label' => 'Specialty Doors Introduction',
                                'name' => 'specialty_intro',
                                'type' => 'textarea',
                                'default_value' => 'IntelliMortise can also work with these specialty door types:',
                                'rows' => 3,
                                'required' => 0,
                            ),
                            array(
                                'key' => 'field_mortise_specialty_items',
                                'label' => 'Specialty Door Items',
                                'name' => 'specialty_items',
                                'type' => 'repeater',
                                'layout' => 'table',
                                'min' => 0,
                                'button_label' => 'Add Compatibility Item',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_mortise_specialty_item_text',
                                        'label' => 'Item Text',
                                        'name' => 'item_text',
                                        'type' => 'text',
                                        'required' => 0,
                                    ),
                                ),
                            ),
                            array(
                                'key' => 'field_mortise_specialty_tip',
                                'label' => 'Specialty Doors Tip',
                                'name' => 'specialty_tip',
                                'type' => 'textarea',
                                'default_value' => 'For specialty applications, our technical team can provide guidance on preparation and installation to ensure proper fit and function.',
                                'rows' => 3,
                                'required' => 0,
                            ),
                        ),
                    ),
                    // Not Compatible Tab
                    array(
                        'key' => 'field_mortise_not_compatible',
                        'label' => 'Not Compatible',
                        'name' => 'not_compatible',
                        'type' => 'group',
                        'layout' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_mortise_not_compatible_title',
                                'label' => 'Not Compatible Title',
                                'name' => 'not_compatible_title',
                                'type' => 'text',
                                'default_value' => 'Not Recommended For',
                                'required' => 0,
                            ),
                            array(
                                'key' => 'field_mortise_not_compatible_intro',
                                'label' => 'Not Compatible Introduction',
                                'name' => 'not_compatible_intro',
                                'type' => 'textarea',
                                'default_value' => 'The IntelliMortise is not ideal for these applications:',
                                'rows' => 3,
                                'required' => 0,
                            ),
                            array(
                                'key' => 'field_mortise_not_compatible_items',
                                'label' => 'Not Compatible Items',
                                'name' => 'not_compatible_items',
                                'type' => 'repeater',
                                'layout' => 'table',
                                'min' => 0,
                                'button_label' => 'Add Compatibility Item',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_mortise_not_compatible_item_text',
                                        'label' => 'Item Text',
                                        'name' => 'item_text',
                                        'type' => 'text',
                                        'required' => 0,
                                    ),
                                ),
                            ),
                            array(
                                'key' => 'field_mortise_not_compatible_tip',
                                'label' => 'Not Compatible Tip',
                                'name' => 'not_compatible_tip',
                                'type' => 'textarea',
                                'default_value' => 'Not sure which 33Lock solution is right for your application? Contact our team with photos of your existing setup for personalized recommendations.',
                                'rows' => 3,
                                'required' => 0,
                            ),
                        ),
                    ),
                ),
            ),
            
            // Installation Section
            array(
                'key' => 'field_mortise_installation_section',
                'label' => 'Installation Section',
                'name' => 'mortise_installation_section',
                'type' => 'group',
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'field_mortise_installation_title',
                        'label' => 'Installation Section Title',
                        'name' => 'installation_title',
                        'type' => 'text',
                        'default_value' => '15-Minute Installation Process',
                        'required' => 0,
                    ),
                    array(
                        'key' => 'field_mortise_installation_steps',
                        'label' => 'Installation Steps',
                        'name' => 'installation_steps',
                        'type' => 'repeater',
                        'layout' => 'block',
                        'min' => 0,
                        'button_label' => 'Add Installation Step',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_mortise_step_number',
                                'label' => 'Step Number',
                                'name' => 'step_number',
                                'type' => 'text',
                                'default_value' => '1',
                                'required' => 0,
                            ),
                            array(
                                'key' => 'field_mortise_step_title',
                                'label' => 'Step Title',
                                'name' => 'step_title',
                                'type' => 'text',
                                'required' => 0,
                            ),
                            array(
                                'key' => 'field_mortise_step_description',
                                'label' => 'Step Description',
                                'name' => 'step_description',
                                'type' => 'textarea',
                                'rows' => 3,
                                'required' => 0,
                            ),
                            array(
                                'key' => 'field_mortise_step_tip',
                                'label' => 'Step Tip (Optional)',
                                'name' => 'step_tip',
                                'type' => 'textarea',
                                'rows' => 3,
                                'required' => 0,
                                'instructions' => 'Add a helpful tip for this step (optional)',
                            ),
                        ),
                    ),
                ),
            ),
            
            // Testimonial Section
            array(
                'key' => 'field_mortise_testimonial_section',
                'label' => 'Testimonial Section',
                'name' => 'mortise_testimonial_section',
                'type' => 'group',
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'field_mortise_testimonial_title',
                        'label' => 'Testimonial Section Title',
                        'name' => 'testimonial_title',
                        'type' => 'text',
                        'default_value' => 'What Our Customers Say',
                        'required' => 0,
                    ),
                    array(
                        'key' => 'field_mortise_testimonials',
                        'label' => 'Testimonials',
                        'name' => 'testimonials',
                        'type' => 'repeater',
                        'layout' => 'block',
                        'min' => 0,
                        'button_label' => 'Add Testimonial',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_mortise_testimonial_text',
                                'label' => 'Testimonial Text',
                                'name' => 'testimonial_text',
                                'type' => 'textarea',
                                'rows' => 4,
                                'required' => 0,
                            ),
                            array(
                                'key' => 'field_mortise_testimonial_name',
                                'label' => 'Name',
                                'name' => 'testimonial_name',
                                'type' => 'text',
                                'required' => 0,
                            ),
                            array(
                                'key' => 'field_mortise_testimonial_position',
                                'label' => 'Position/Company',
                                'name' => 'testimonial_position',
                                'type' => 'text',
                                'required' => 0,
                            ),
                            array(
                                'key' => 'field_mortise_testimonial_avatar',
                                'label' => 'Avatar Image',
                                'name' => 'testimonial_avatar',
                                'type' => 'image',
                                'return_format' => 'url',
                                'preview_size' => 'thumbnail',
                                'required' => 0,
                            ),
                        ),
                    ),
                ),
            ),
            
            // FAQ Section
            array(
                'key' => 'field_mortise_faq_section',
                'label' => 'FAQ Section',
                'name' => 'mortise_faq_section',
                'type' => 'group',
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'field_mortise_faq_title',
                        'label' => 'FAQ Section Title',
                        'name' => 'faq_title',
                        'type' => 'text',
                        'default_value' => 'Frequently Asked Questions',
                        'required' => 0,
                    ),
                    array(
                        'key' => 'field_mortise_faqs',
                        'label' => 'FAQs',
                        'name' => 'faqs',
                        'type' => 'repeater',
                        'layout' => 'block',
                        'min' => 0,
                        'button_label' => 'Add FAQ',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_mortise_faq_question',
                                'label' => 'Question',
                                'name' => 'question',
                                'type' => 'text',
                                'required' => 0,
                            ),
                            array(
                                'key' => 'field_mortise_faq_answer',
                                'label' => 'Answer',
                                'name' => 'answer',
                                'type' => 'wysiwyg',
                                'required' => 0,
                                'tabs' => 'all',
                                'toolbar' => 'basic',
                                'media_upload' => 0,
                            ),
                        ),
                    ),
                ),
            ),
            
            // Related Products Section
            array(
                'key' => 'field_mortise_related_products_section',
                'label' => 'Related Products Section',
                'name' => 'mortise_related_products_section',
                'type' => 'group',
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'field_mortise_related_products_title',
                        'label' => 'Related Products Section Title',
                        'name' => 'related_products_title',
                        'type' => 'text',
                        'default_value' => 'Complete your smart access ecosystem',
                        'required' => 0,
                    ),
                    array(
                        'key' => 'field_mortise_related_products',
                        'label' => 'Related Products',
                        'name' => 'related_products',
                        'type' => 'repeater',
                        'layout' => 'block',
                        'min' => 0,
                        'max' => 3,
                        'button_label' => 'Add Related Product',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_mortise_related_product_title',
                                'label' => 'Product Title',
                                'name' => 'product_title',
                                'type' => 'text',
                                'required' => 0,
                            ),
                            array(
                                'key' => 'field_mortise_related_product_description',
                                'label' => 'Product Description',
                                'name' => 'product_description',
                                'type' => 'text',
                                'required' => 0,
                            ),
                            array(
                                'key' => 'field_mortise_related_product_image',
                                'label' => 'Product Image',
                                'name' => 'product_image',
                                'type' => 'image',
                                'return_format' => 'url',
                                'preview_size' => 'thumbnail',
                                'required' => 0,
                            ),
                            array(
                                'key' => 'field_mortise_related_product_url',
                                'label' => 'Product URL',
                                'name' => 'product_url',
                                'type' => 'text',
                                'required' => 0,
                            ),
                        ),
                    ),
                ),
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'page-templates/intelli-mortise-template.php',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));
}