<?php
/**
 * ACF fields for Lock Series Template
 */

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group(array(
        'key' => 'group_lock_series_template',
        'title' => 'Lock Series Template',
        'fields' => array(
            // Hero Section Fields
            array(
                'key' => 'field_lock_hero_title',
                'label' => 'Hero Title',
                'name' => 'lock_hero_title',
                'type' => 'text',
                'instructions' => 'Enter the main title for the hero section',
                'default_value' => 'One Series. Four Ways to Unlock Smarter Hospitality',
                'required' => 1,
            ),
            array(
                'key' => 'field_lock_hero_subtitle',
                'label' => 'Hero Subtitle',
                'name' => 'lock_hero_subtitle',
                'type' => 'text',
                'instructions' => 'Enter the subtitle for the hero section',
                'default_value' => 'Keyless access built for hotels, vacation rentals, and multifamily doors of every type.',
                'required' => 0,
            ),
            array(
                'key' => 'field_lock_hero_bg',
                'label' => 'Hero Background Image',
                'name' => 'lock_hero_bg',
                'type' => 'image',
                'instructions' => 'Upload a background image for the hero section (recommended: 1920x1080px)',
                'return_format' => 'url',
                'preview_size' => 'medium',
                'required' => 0,
            ),
            array(
                'key' => 'field_lock_primary_cta_text',
                'label' => 'Primary CTA Text',
                'name' => 'lock_primary_cta_text',
                'type' => 'text',
                'instructions' => 'Enter the text for the primary call-to-action button',
                'default_value' => 'Compare Models',
                'required' => 0,
            ),
            array(
                'key' => 'field_lock_primary_cta_url',
                'label' => 'Primary CTA URL',
                'name' => 'lock_primary_cta_url',
                'type' => 'text',
                'instructions' => 'Enter the URL for the primary call-to-action button',
                'default_value' => '#compare',
                'required' => 0,
            ),
            array(
                'key' => 'field_lock_secondary_cta_text',
                'label' => 'Secondary CTA Text',
                'name' => 'lock_secondary_cta_text',
                'type' => 'text',
                'instructions' => 'Enter the text for the secondary call-to-action button',
                'default_value' => 'Request a Quote',
                'required' => 0,
            ),
            array(
                'key' => 'field_lock_secondary_cta_url',
                'label' => 'Secondary CTA URL',
                'name' => 'lock_secondary_cta_url',
                'type' => 'text',
                'instructions' => 'Enter the URL for the secondary call-to-action button',
                'default_value' => '/contact',
                'required' => 0,
            ),
            
            // About Section Fields
            array(
                'key' => 'field_lock_about_title',
                'label' => 'About Section Title',
                'name' => 'lock_about_title',
                'type' => 'text',
                'instructions' => 'Enter the title for the About section',
                'default_value' => 'About 33 Lock',
                'required' => 0,
            ),
            array(
                'key' => 'field_lock_about_content',
                'label' => 'About Content',
                'name' => 'lock_about_content',
                'type' => 'textarea',
                'instructions' => 'Enter the main content for the About section',
                'default_value' => '33 Lock is a Vancouver-born access-control company that helps property operators cut costs and delight guests with reliable, cloud-connected smart locks. Our hardware-plus-software platform already secures thousands of hotel rooms, vacation rentals, and multifamily units across North America—delivering safer entry, easier management, and rapid ROI.',
                'required' => 0,
                'rows' => 4,
            ),
            array(
                'key' => 'field_lock_about_stats',
                'label' => 'About Stats',
                'name' => 'lock_about_stats',
                'type' => 'repeater',
                'instructions' => 'Add statistics for the About section',
                'required' => 0,
                'min' => 0,
                'max' => 6,
                'layout' => 'table',
                'button_label' => 'Add Stat',
                'sub_fields' => array(
                    array(
                        'key' => 'field_lock_about_stat_number',
                        'label' => 'Stat Number',
                        'name' => 'stat_number',
                        'type' => 'text',
                        'required' => 0,
                        'instructions' => 'The displayed statistic (e.g., "1000s", "99.9%")',
                    ),
                    array(
                        'key' => 'field_lock_about_stat_label',
                        'label' => 'Stat Label',
                        'name' => 'stat_label',
                        'type' => 'text',
                        'required' => 0,
                        'instructions' => 'Description of the statistic (e.g., "of units secured")',
                    ),
                ),
            ),
            
            // Product Lineup Fields - IntelliMortise
            array(
                'key' => 'field_lock_mortise_title',
                'label' => 'IntelliMortise Title',
                'name' => 'lock_mortise_title',
                'type' => 'text',
                'instructions' => 'Enter the title for the IntelliMortise product',
                'default_value' => 'IntelliMortise',
                'required' => 0,
            ),
            array(
                'key' => 'field_lock_mortise_subtitle',
                'label' => 'IntelliMortise Subtitle',
                'name' => 'lock_mortise_subtitle',
                'type' => 'text',
                'instructions' => 'Enter the subtitle for the IntelliMortise product',
                'default_value' => 'Flagship security for new builds',
                'required' => 0,
            ),
            array(
                'key' => 'field_lock_mortise_image',
                'label' => 'IntelliMortise Image',
                'name' => 'lock_mortise_image',
                'type' => 'image',
                'instructions' => 'Upload an image for the IntelliMortise product',
                'return_format' => 'url',
                'preview_size' => 'medium',
                'required' => 0,
            ),
            array(
                'key' => 'field_lock_mortise_features',
                'label' => 'IntelliMortise Features',
                'name' => 'lock_mortise_features',
                'type' => 'repeater',
                'instructions' => 'Add features for the IntelliMortise product',
                'required' => 0,
                'min' => 0,
                'max' => 5,
                'layout' => 'table',
                'button_label' => 'Add Feature',
                'sub_fields' => array(
                    array(
                        'key' => 'field_lock_mortise_feature_text',
                        'label' => 'Feature Text',
                        'name' => 'feature_text',
                        'type' => 'text',
                        'required' => 0,
                    ),
                ),
            ),
            array(
                'key' => 'field_lock_mortise_recommendation',
                'label' => 'IntelliMortise Recommendation',
                'name' => 'lock_mortise_recommendation',
                'type' => 'text',
                'instructions' => 'Enter the recommendation for the IntelliMortise product',
                'default_value' => 'Luxury guest rooms, exterior doors.',
                'required' => 0,
            ),
            array(
                'key' => 'field_lock_mortise_url',
                'label' => 'IntelliMortise URL',
                'name' => 'lock_mortise_url',
                'type' => 'text',
                'instructions' => 'Enter the URL for the IntelliMortise product details',
                'default_value' => '/locks/intellimortise',
                'required' => 0,
            ),
            
            // Product Lineup Fields - IntelliLever
            array(
                'key' => 'field_lock_lever_title',
                'label' => 'IntelliLever Title',
                'name' => 'lock_lever_title',
                'type' => 'text',
                'instructions' => 'Enter the title for the IntelliLever product',
                'default_value' => 'IntelliLever',
                'required' => 0,
            ),
            array(
                'key' => 'field_lock_lever_subtitle',
                'label' => 'IntelliLever Subtitle',
                'name' => 'lock_lever_subtitle',
                'type' => 'text',
                'instructions' => 'Enter the subtitle for the IntelliLever product',
                'default_value' => 'Retrofit in minutes',
                'required' => 0,
            ),
            array(
                'key' => 'field_lock_lever_image',
                'label' => 'IntelliLever Image',
                'name' => 'lock_lever_image',
                'type' => 'image',
                'instructions' => 'Upload an image for the IntelliLever product',
                'return_format' => 'url',
                'preview_size' => 'medium',
                'required' => 0,
            ),
            array(
                'key' => 'field_lock_lever_features',
                'label' => 'IntelliLever Features',
                'name' => 'lock_lever_features',
                'type' => 'repeater',
                'instructions' => 'Add features for the IntelliLever product',
                'required' => 0,
                'min' => 0,
                'max' => 5,
                'layout' => 'table',
                'button_label' => 'Add Feature',
                'sub_fields' => array(
                    array(
                        'key' => 'field_lock_lever_feature_text',
                        'label' => 'Feature Text',
                        'name' => 'feature_text',
                        'type' => 'text',
                        'required' => 0,
                    ),
                ),
            ),
            array(
                'key' => 'field_lock_lever_recommendation',
                'label' => 'IntelliLever Recommendation',
                'name' => 'lock_lever_recommendation',
                'type' => 'text',
                'instructions' => 'Enter the recommendation for the IntelliLever product',
                'default_value' => 'Fast upgrades in boutique hotels & rentals.',
                'required' => 0,
            ),
            array(
                'key' => 'field_lock_lever_url',
                'label' => 'IntelliLever URL',
                'name' => 'lock_lever_url',
                'type' => 'text',
                'instructions' => 'Enter the URL for the IntelliLever product details',
                'default_value' => '/locks/intellilever',
                'required' => 0,
            ),
            
            // Product Lineup Fields - IntelliBolt
            array(
                'key' => 'field_lock_bolt_title',
                'label' => 'IntelliBolt Title',
                'name' => 'lock_bolt_title',
                'type' => 'text',
                'instructions' => 'Enter the title for the IntelliBolt product',
                'default_value' => 'IntelliBolt',
                'required' => 0,
            ),
            array(
                'key' => 'field_lock_bolt_subtitle',
                'label' => 'IntelliBolt Subtitle',
                'name' => 'lock_bolt_subtitle',
                'type' => 'text',
                'instructions' => 'Enter the subtitle for the IntelliBolt product',
                'default_value' => 'Surface-mount versatility',
                'required' => 0,
            ),
            array(
                'key' => 'field_lock_bolt_image',
                'label' => 'IntelliBolt Image',
                'name' => 'lock_bolt_image',
                'type' => 'image',
                'instructions' => 'Upload an image for the IntelliBolt product',
                'return_format' => 'url',
                'preview_size' => 'medium',
                'required' => 0,
            ),
            array(
                'key' => 'field_lock_bolt_features',
                'label' => 'IntelliBolt Features',
                'name' => 'lock_bolt_features',
                'type' => 'repeater',
                'instructions' => 'Add features for the IntelliBolt product',
                'required' => 0,
                'min' => 0,
                'max' => 5,
                'layout' => 'table',
                'button_label' => 'Add Feature',
                'sub_fields' => array(
                    array(
                        'key' => 'field_lock_bolt_feature_text',
                        'label' => 'Feature Text',
                        'name' => 'feature_text',
                        'type' => 'text',
                        'required' => 0,
                    ),
                ),
            ),
            array(
                'key' => 'field_lock_bolt_recommendation',
                'label' => 'IntelliBolt Recommendation',
                'name' => 'lock_bolt_recommendation',
                'type' => 'text',
                'instructions' => 'Enter the recommendation for the IntelliBolt product',
                'default_value' => 'Glass, metal, or atypical doors.',
                'required' => 0,
            ),
            array(
                'key' => 'field_lock_bolt_url',
                'label' => 'IntelliBolt URL',
                'name' => 'lock_bolt_url',
                'type' => 'text',
                'instructions' => 'Enter the URL for the IntelliBolt product details',
                'default_value' => '/locks/intellibolt',
                'required' => 0,
            ),
            
            // Product Lineup Fields - IntelliReader
            array(
                'key' => 'field_lock_reader_title',
                'label' => 'IntelliReader Title',
                'name' => 'lock_reader_title',
                'type' => 'text',
                'instructions' => 'Enter the title for the IntelliReader product',
                'default_value' => 'IntelliReader',
                'required' => 0,
            ),
            array(
                'key' => 'field_lock_reader_subtitle',
                'label' => 'IntelliReader Subtitle',
                'name' => 'lock_reader_subtitle',
                'type' => 'text',
                'instructions' => 'Enter the subtitle for the IntelliReader product',
                'default_value' => 'Common-area controller',
                'required' => 0,
            ),
            array(
                'key' => 'field_lock_reader_image',
                'label' => 'IntelliReader Image',
                'name' => 'lock_reader_image',
                'type' => 'image',
                'instructions' => 'Upload an image for the IntelliReader product',
                'return_format' => 'url',
                'preview_size' => 'medium',
                'required' => 0,
            ),
            array(
                'key' => 'field_lock_reader_features',
                'label' => 'IntelliReader Features',
                'name' => 'lock_reader_features',
                'type' => 'repeater',
                'instructions' => 'Add features for the IntelliReader product',
                'required' => 0,
                'min' => 0,
                'max' => 5,
                'layout' => 'table',
                'button_label' => 'Add Feature',
                'sub_fields' => array(
                    array(
                        'key' => 'field_lock_reader_feature_text',
                        'label' => 'Feature Text',
                        'name' => 'feature_text',
                        'type' => 'text',
                        'required' => 0,
                    ),
                ),
            ),
            array(
                'key' => 'field_lock_reader_recommendation',
                'label' => 'IntelliReader Recommendation',
                'name' => 'lock_reader_recommendation',
                'type' => 'text',
                'instructions' => 'Enter the recommendation for the IntelliReader product',
                'default_value' => 'Lobbies, elevators, staff rooms.',
                'required' => 0,
            ),
            array(
                'key' => 'field_lock_reader_url',
                'label' => 'IntelliReader URL',
                'name' => 'lock_reader_url',
                'type' => 'text',
                'instructions' => 'Enter the URL for the IntelliReader product details',
                'default_value' => '/locks/intellireader',
                'required' => 0,
            ),
            
            // Deployment Steps
            array(
                'key' => 'field_lock_deploy_title',
                'label' => 'Deployment Section Title',
                'name' => 'lock_deploy_title',
                'type' => 'text',
                'instructions' => 'Enter the title for the deployment section',
                'default_value' => 'How to Deploy',
                'required' => 0,
            ),
            array(
                'key' => 'field_lock_deploy_steps',
                'label' => 'Deployment Steps',
                'name' => 'lock_deploy_steps',
                'type' => 'repeater',
                'instructions' => 'Add steps for deploying the lock system',
                'required' => 0,
                'min' => 1,
                'max' => 6,
                'layout' => 'block',
                'button_label' => 'Add Step',
                'sub_fields' => array(
                    array(
                        'key' => 'field_lock_deploy_step_number',
                        'label' => 'Step Number',
                        'name' => 'step_number',
                        'type' => 'number',
                        'required' => 1,
                        'default_value' => 1,
                        'min' => 1,
                    ),
                    array(
                        'key' => 'field_lock_deploy_step_title',
                        'label' => 'Step Title',
                        'name' => 'step_title',
                        'type' => 'text',
                        'required' => 1,
                    ),
                    array(
                        'key' => 'field_lock_deploy_step_description',
                        'label' => 'Step Description',
                        'name' => 'step_description',
                        'type' => 'text',
                        'required' => 1,
                    ),
                    array(
                        'key' => 'field_lock_deploy_step_icon',
                        'label' => 'Step Icon',
                        'name' => 'step_icon',
                        'type' => 'select',
                        'required' => 0,
                        'choices' => array(
                            'clipboard-check' => 'Clipboard Check',
                            'truck' => 'Truck/Shipping',
                            'tools' => 'Tools/Installation',
                            'cog' => 'Gear/Settings',
                            'upload' => 'Upload/Cloud',
                            'server' => 'Server/System',
                            'wifi' => 'WiFi/Connection',
                            'key' => 'Key/Access',
                            'lock' => 'Lock',
                            'users' => 'Users/Team',
                            'mobile' => 'Mobile Phone',
                            'calendar' => 'Calendar/Schedule',
                            'database' => 'Database',
                            'chart' => 'Chart/Analytics',
                            'code' => 'Code/API',
                        ),
                        'default_value' => 'clipboard-check',
                        'allow_null' => 0,
                        'multiple' => 0,
                        'ui' => 1,
                        'return_format' => 'value',
                    ),
                ),
            ),
            
            // Benefits Section
            array(
                'key' => 'field_lock_benefits',
                'label' => 'Benefits',
                'name' => 'lock_benefits',
                'type' => 'repeater',
                'instructions' => 'Add benefits of choosing Intelli Series',
                'required' => 0,
                'min' => 0,
                'max' => 6,
                'layout' => 'block',
                'button_label' => 'Add Benefit',
                'sub_fields' => array(
                    array(
                        'key' => 'field_lock_benefit_title',
                        'label' => 'Benefit Title',
                        'name' => 'benefit_title',
                        'type' => 'text',
                        'required' => 0,
                    ),
                    array(
                        'key' => 'field_lock_benefit_description',
                        'label' => 'Benefit Description',
                        'name' => 'benefit_description',
                        'type' => 'textarea',
                        'required' => 0,
                        'rows' => 3,
                    ),
                ),
            ),
            
            // Testimonial Fields
            array(
                'key' => 'field_lock_testimonial_quote',
                'label' => 'Testimonial Quote',
                'name' => 'lock_testimonial_quote',
                'type' => 'textarea',
                'instructions' => 'Enter a customer testimonial quote',
                'default_value' => '33 Lock\'s IntelliMortise cut our check-in time in half and slashed lost-key incidents to zero.',
                'required' => 0,
                'rows' => 3,
            ),
            array(
                'key' => 'field_lock_testimonial_author',
                'label' => 'Testimonial Author',
                'name' => 'lock_testimonial_author',
                'type' => 'text',
                'instructions' => 'Enter the author of the testimonial',
                'default_value' => 'Lori V., GM, Seaside Resort',
                'required' => 0,
            ),
            
            // Partner Logos
            array(
                'key' => 'field_lock_partner_logos',
                'label' => 'Partner Logos',
                'name' => 'lock_partner_logos',
                'type' => 'repeater',
                'instructions' => 'Add partner logos',
                'required' => 0,
                'min' => 0,
                'max' => 6,
                'layout' => 'table',
                'button_label' => 'Add Partner',
                'sub_fields' => array(
                    array(
                        'key' => 'field_lock_partner_name',
                        'label' => 'Partner Name',
                        'name' => 'partner_name',
                        'type' => 'text',
                        'required' => 0,
                    ),
                    array(
                        'key' => 'field_lock_partner_logo',
                        'label' => 'Partner Logo',
                        'name' => 'partner_logo',
                        'type' => 'image',
                        'return_format' => 'url',
                        'preview_size' => 'thumbnail',
                        'required' => 0,
                    ),
                ),
            ),
            
            // Final CTA Fields
            array(
                'key' => 'field_lock_final_cta_text',
                'label' => 'Final CTA Text',
                'name' => 'lock_final_cta_text',
                'type' => 'text',
                'instructions' => 'Enter the text for the final call-to-action',
                'default_value' => 'Ready to modernise every door?',
                'required' => 0,
            ),
            array(
                'key' => 'field_lock_final_cta_button_text',
                'label' => 'Final CTA Button Text',
                'name' => 'lock_final_cta_button_text',
                'type' => 'text',
                'instructions' => 'Enter the text for the final call-to-action button',
                'default_value' => 'Get My Custom Quote',
                'required' => 0,
            ),
            array(
                'key' => 'field_lock_final_cta_button_url',
                'label' => 'Final CTA Button URL',
                'name' => 'lock_final_cta_button_url',
                'type' => 'text',
                'instructions' => 'Enter the URL for the final call-to-action button',
                'default_value' => '/contact',
                'required' => 0,
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'page-templates/lock-series-template.php',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));
}