<?php
/**
 * ACF fields for Modern 33Lock Home Template
 */

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group(array(
        'key' => 'group_modern_home_template',
        'title' => 'Modern 33Lock Home',
        'fields' => array(
            // Hero Section
            array(
                'key' => 'field_modern_hero_section',
                'label' => 'Hero Section',
                'name' => 'hero_section',
                'type' => 'group',
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'field_hero_headline',
                        'label' => 'Headline (H1)',
                        'name' => 'hero_headline',
                        'type' => 'text',
                        'default_value' => 'Smart-Lock Access that Guests Love—at a Price Owners Trust',
                        'required' => 1,
                    ),
                    array(
                        'key' => 'field_hero_subhead',
                        'label' => 'Subheading',
                        'name' => 'hero_subhead',
                        'type' => 'textarea',
                        'default_value' => 'Replace legacy hardware in < 15 minutes and manage every door—online or offline—from one cloud dashboard.',
                        'rows' => 3,
                        'required' => 0,
                    ),
                    array(
                        'key' => 'field_hero_image',
                        'label' => 'Hero Background Image',
                        'name' => 'hero_image',
                        'type' => 'image',
                        'return_format' => 'id',
                        'preview_size' => 'medium',
                        'instructions' => 'Full-bleed hero image of hotel door opening (recommended: 1920×1080px)',
                        'required' => 0,
                    ),
                    array(
                        'key' => 'field_primary_cta_text',
                        'label' => 'Primary CTA Button Text',
                        'name' => 'primary_cta_text',
                        'type' => 'text',
                        'default_value' => 'Book a Demo',
                        'required' => 0,
                    ),
                    array(
                        'key' => 'field_primary_cta_url',
                        'label' => 'Primary CTA Button URL',
                        'name' => 'primary_cta_url',
                        'type' => 'text',
                        'default_value' => '#contact',
                        'required' => 0,
                    ),
                    array(
                        'key' => 'field_secondary_cta_text',
                        'label' => 'Secondary CTA Button Text',
                        'name' => 'secondary_cta_text',
                        'type' => 'text',
                        'default_value' => 'Download Spec Sheet',
                        'required' => 0,
                    ),
                    array(
                        'key' => 'field_secondary_cta_url',
                        'label' => 'Secondary CTA Button URL',
                        'name' => 'secondary_cta_url',
                        'type' => 'text',
                        'default_value' => '#specs',
                        'required' => 0,
                    ),
                ),
            ),
            
            // Trust Signals Section
            array(
                'key' => 'field_trust_signals_section',
                'label' => 'Trust Signals Section',
                'name' => 'trust_signals_section',
                'type' => 'group',
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'field_trust_signals',
                        'label' => 'Trust Signals',
                        'name' => 'trust_signals',
                        'type' => 'repeater',
                        'layout' => 'table',
                        'min' => 0,
                        'max' => 4,
                        'button_label' => 'Add Trust Signal',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_trust_signal_icon',
                                'label' => 'Icon (SVG)',
                                'name' => 'icon',
                                'type' => 'textarea',
                                'rows' => 3,
                                'required' => 0,
                            ),
                            array(
                                'key' => 'field_trust_signal_stat',
                                'label' => 'Statistic',
                                'name' => 'stat',
                                'type' => 'text',
                                'required' => 0,
                            ),
                        ),
                    ),
                ),
            ),
            
            // Benefits Section
            array(
                'key' => 'field_benefits_section',
                'label' => 'Benefits Section',
                'name' => 'benefits_section',
                'type' => 'group',
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'field_benefits_title',
                        'label' => 'Section Title',
                        'name' => 'benefits_title',
                        'type' => 'text',
                        'default_value' => 'Why 33 Lock?',
                        'required' => 0,
                    ),
                    array(
                        'key' => 'field_benefits',
                        'label' => 'Benefits',
                        'name' => 'benefits',
                        'type' => 'repeater',
                        'layout' => 'block',
                        'min' => 0,
                        'max' => 4,
                        'button_label' => 'Add Benefit',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_benefit_icon',
                                'label' => 'Icon (Emoji)',
                                'name' => 'icon',
                                'type' => 'text',
                                'default_value' => '🛠️',
                                'required' => 0,
                            ),
                            array(
                                'key' => 'field_benefit_headline',
                                'label' => 'Headline',
                                'name' => 'headline',
                                'type' => 'text',
                                'required' => 0,
                            ),
                            array(
                                'key' => 'field_benefit_description',
                                'label' => 'Description',
                                'name' => 'description',
                                'type' => 'text',
                                'required' => 0,
                            ),
                        ),
                    ),
                ),
            ),
            
            // Products Section
            array(
                'key' => 'field_products_section',
                'label' => 'Products Section',
                'name' => 'products_section',
                'type' => 'group',
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'field_products_title',
                        'label' => 'Section Title',
                        'name' => 'products_title',
                        'type' => 'text',
                        'default_value' => 'Choose the Lock That Fits',
                        'required' => 0,
                    ),
                    array(
                        'key' => 'field_products',
                        'label' => 'Products',
                        'name' => 'products',
                        'type' => 'repeater',
                        'layout' => 'block',
                        'min' => 0,
                        'max' => 4,
                        'button_label' => 'Add Product',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_product_image',
                                'label' => 'Product Image',
                                'name' => 'image',
                                'type' => 'image',
                                'return_format' => 'url',
                                'preview_size' => 'medium',
                                'required' => 0,
                            ),
                            array(
                                'key' => 'field_product_title',
                                'label' => 'Product Title',
                                'name' => 'title',
                                'type' => 'text',
                                'required' => 0,
                            ),
                            array(
                                'key' => 'field_product_tagline',
                                'label' => 'Product Tagline',
                                'name' => 'tagline',
                                'type' => 'text',
                                'required' => 0,
                            ),
                            array(
                                'key' => 'field_product_features',
                                'label' => 'Product Features',
                                'name' => 'features',
                                'type' => 'text',
                                'required' => 0,
                            ),
                            array(
                                'key' => 'field_product_url',
                                'label' => 'Product URL',
                                'name' => 'url',
                                'type' => 'text',
                                'required' => 0,
                            ),
                        ),
                    ),
                ),
            ),
            
            // Industry Sections
            array(
                'key' => 'field_industry_sections',
                'label' => 'Industry Sections',
                'name' => 'industry_sections',
                'type' => 'group',
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'field_industry_title',
                        'label' => 'Section Title',
                        'name' => 'industry_title',
                        'type' => 'text',
                        'default_value' => 'Built for Your Property',
                        'required' => 0,
                    ),
                    // Hotels
                    array(
                        'key' => 'field_hotels_image',
                        'label' => 'Hotels & Resorts Image',
                        'name' => 'hotels_image',
                        'type' => 'image',
                        'return_format' => 'url',
                        'preview_size' => 'medium',
                        'required' => 0,
                    ),
                    array(
                        'key' => 'field_hotels_text',
                        'label' => 'Hotels & Resorts Text',
                        'name' => 'hotels_text',
                        'type' => 'textarea',
                        'default_value' => 'Cut front-desk queues and meet guest expectations for mobile access.',
                        'rows' => 3,
                        'required' => 0,
                    ),
                    array(
                        'key' => 'field_hotels_link',
                        'label' => 'Hotels & Resorts Link',
                        'name' => 'hotels_link',
                        'type' => 'text',
                        'default_value' => '/solutions/hotels',
                        'required' => 0,
                    ),
                    // Vacation Rentals
                    array(
                        'key' => 'field_vacation_image',
                        'label' => 'Vacation Rentals Image',
                        'name' => 'vacation_image',
                        'type' => 'image',
                        'return_format' => 'url',
                        'preview_size' => 'medium',
                        'required' => 0,
                    ),
                    array(
                        'key' => 'field_vacation_text',
                        'label' => 'Vacation Rentals Text',
                        'name' => 'vacation_text',
                        'type' => 'textarea',
                        'default_value' => 'Automate back-to-back turnovers with self-expiring PINs—no more key exchanges.',
                        'rows' => 3,
                        'required' => 0,
                    ),
                    array(
                        'key' => 'field_vacation_link',
                        'label' => 'Vacation Rentals Link',
                        'name' => 'vacation_link',
                        'type' => 'text',
                        'default_value' => '/solutions/vacation-rentals',
                        'required' => 0,
                    ),
                    // Student Housing
                    array(
                        'key' => 'field_student_image',
                        'label' => 'Student Housing Image',
                        'name' => 'student_image',
                        'type' => 'image',
                        'return_format' => 'url',
                        'preview_size' => 'medium',
                        'required' => 0,
                    ),
                    array(
                        'key' => 'field_student_text',
                        'label' => 'Student Housing Text',
                        'name' => 'student_text',
                        'type' => 'textarea',
                        'default_value' => 'Issue semester-long credentials and track maintenance staff visits.',
                        'rows' => 3,
                        'required' => 0,
                    ),
                    array(
                        'key' => 'field_student_link',
                        'label' => 'Student Housing Link',
                        'name' => 'student_link',
                        'type' => 'text',
                        'default_value' => '/solutions/student-housing',
                        'required' => 0,
                    ),
                ),
            ),
            
            // Testimonials Section
            array(
                'key' => 'field_testimonials_section',
                'label' => 'Testimonials Section',
                'name' => 'testimonials_section',
                'type' => 'group',
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'field_testimonials',
                        'label' => 'Testimonials',
                        'name' => 'testimonials',
                        'type' => 'repeater',
                        'layout' => 'block',
                        'min' => 0,
                        'max' => 5,
                        'button_label' => 'Add Testimonial',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_testimonial_quote',
                                'label' => 'Quote',
                                'name' => 'quote',
                                'type' => 'textarea',
                                'rows' => 3,
                                'required' => 0,
                            ),
                            array(
                                'key' => 'field_testimonial_author',
                                'label' => 'Author',
                                'name' => 'author',
                                'type' => 'text',
                                'required' => 0,
                            ),
                        ),
                    ),
                ),
            ),
            
            // Integrations Section
            array(
                'key' => 'field_integrations_section',
                'label' => 'Integrations Section',
                'name' => 'integrations_section',
                'type' => 'group',
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'field_integrations',
                        'label' => 'Integrations',
                        'name' => 'integrations',
                        'type' => 'repeater',
                        'layout' => 'table',
                        'min' => 0,
                        'max' => 6,
                        'button_label' => 'Add Integration',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_integration_name',
                                'label' => 'Integration Name',
                                'name' => 'name',
                                'type' => 'text',
                                'required' => 0,
                            ),
                            array(
                                'key' => 'field_integration_logo',
                                'label' => 'Integration Logo',
                                'name' => 'logo',
                                'type' => 'image',
                                'return_format' => 'url',
                                'preview_size' => 'thumbnail',
                                'required' => 0,
                            ),
                        ),
                    ),
                ),
            ),
            
            // Resources Section
            array(
                'key' => 'field_resources_section',
                'label' => 'Resources Section',
                'name' => 'resources_section',
                'type' => 'group',
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'field_whitepaper_title',
                        'label' => 'Whitepaper Title',
                        'name' => 'whitepaper_title',
                        'type' => 'text',
                        'default_value' => 'The True Cost of Metal Keys',
                        'required' => 0,
                    ),
                    array(
                        'key' => 'field_whitepaper_url',
                        'label' => 'Whitepaper URL',
                        'name' => 'whitepaper_url',
                        'type' => 'text',
                        'default_value' => '/resources/whitepaper-metal-keys.pdf',
                        'required' => 0,
                    ),
                    array(
                        'key' => 'field_blog_title',
                        'label' => 'Blog Post Title',
                        'name' => 'blog_title',
                        'type' => 'text',
                        'default_value' => 'Offline Access—Why It Matters',
                        'required' => 0,
                    ),
                    array(
                        'key' => 'field_blog_url',
                        'label' => 'Blog Post URL',
                        'name' => 'blog_url',
                        'type' => 'text',
                        'default_value' => '/blog/offline-access',
                        'required' => 0,
                    ),
                    array(
                        'key' => 'field_support_url',
                        'label' => 'Support Center URL',
                        'name' => 'support_url',
                        'type' => 'text',
                        'default_value' => '/support',
                        'required' => 0,
                    ),
                ),
            ),
            
            // Final CTA Section
            array(
                'key' => 'field_final_cta_section',
                'label' => 'Final CTA Section',
                'name' => 'final_cta_section',
                'type' => 'group',
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'field_cta_title',
                        'label' => 'CTA Title',
                        'name' => 'cta_title',
                        'type' => 'text',
                        'default_value' => 'Ready to modernise your access control?',
                        'required' => 0,
                    ),
                    array(
                        'key' => 'field_cta_button_text',
                        'label' => 'CTA Button Text',
                        'name' => 'cta_button_text',
                        'type' => 'text',
                        'default_value' => 'Book a 10-Minute Demo',
                        'required' => 0,
                    ),
                    array(
                        'key' => 'field_cta_url',
                        'label' => 'CTA URL',
                        'name' => 'cta_url',
                        'type' => 'text',
                        'default_value' => '/demo',
                        'required' => 0,
                    ),
                ),
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'page-templates/modern-home-template.php',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));
}